# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$directory\
$character"""

right_format = """
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$maven\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '
disabled = true

[character]
format = " $symbol "
success_symbol = "[❯](bold fg:5)"
error_symbol = "[❯](bold 209)"
vimcmd_symbol = "[■](bold fg:5)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green'

[env_var.http_proxy]
format = "[⇄]($style) "
style = "italic green"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = ""
read_only = " ◈"
use_os_path_sep = true
style = "fg:5"
format = '[\[$path\]]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold fg:5'
repo_root_format = '[\[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path\]]($style)[$read_only]($read_only_style)'

[direnv]
disabled = false

[opa]
disabled = true

[cmd_duration]
format = "[◄ $duration ](italic white)"

[time]
disabled = true

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[△](bold italic bright-blue)"
style = "italic bright-blue"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = true

[git_status]
disabled = false
style = "bold italic bright-blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪](italic bright-magenta)"
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
diverged = "[◇│[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌](italic bright-yellow)"
stashed = "[◈](italic white)"
modified = "[●](italic yellow)"
staged = "[▪┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎](italic bright-blue)"
deleted = "[✕](italic red)"

[deno]
disabled = true

[lua]
disabled = true

[kubernetes]
disabled = true

[nodejs]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
detect_extensions = []
detect_folders = []
detect_files = []

[aws]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[memory_usage]
symbol = "▪▫▪ "
format = " mem [${ram}( ${swap})]($style)"


[[claude_context.display]]
threshold = 0
hidden = false
